services:
  # for dev
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=we-need-to-eat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5438:5432

volumes:
  postgres-data:
